### ISSUE TITLE
可以加一下联系方式嘛

### ISSUE THREAD

**Issue by KirakiKiraki** [Jim-Rae/blogs#3]
可以加一下联系方式嘛

**Comment by Jim-Rae** [comment]
有什么事吗？

**Comment by Jim-Rae** [comment]
@KirakiKiraki  有什么事吗？

**Comment by KirakiKiraki** [comment]
你好，我是一个大二的学生，在网上找到了你们的那个跳蚤市场的代码，但是数据跑不出来，就想着找您问一下可以嘛


---原始邮件---
发件人: &quot;Jim ***@***.***&gt;
发送时间: 2022年6月8日(周三) 下午2:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jim-Rae/blogs] 可以加一下联系方式嘛 (Issue #3)




 
有什么事吗？
 
&mdash;

**Comment by Jim-Rae** [comment]
@KirakiKiraki  2432340714，我qq

**Comment by KirakiKiraki** [comment]
加你了哦，我叫杨兰正


---原始邮件---
发件人: &quot;Jim ***@***.***&gt;
发送时间: 2022年6月8日(周三) 下午2:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jim-Rae/blogs] 可以加一下联系方式嘛 (Issue #3)




 
@KirakiKiraki  2432340714，我qq
 
&mdash;
